// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ChessRogueGameAeonInfo.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from ChessRogueGameAeonInfo.proto</summary>
  public static partial class ChessRogueGameAeonInfoReflection {

    #region Descriptor
    /// <summary>File descriptor for ChessRogueGameAeonInfo.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ChessRogueGameAeonInfoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChxDaGVzc1JvZ3VlR2FtZUFlb25JbmZvLnByb3RvGhFFQk9JT0lLRkxGSi5w",
            "cm90byJmChZDaGVzc1JvZ3VlR2FtZUFlb25JbmZvEhQKDGdhbWVfYWVvbl9p",
            "ZBgOIAEoDRIhCgtPQUtOR05LQUxQSRgDIAEoCzIMLkVCT0lPSUtGTEZKEhMK",
            "C0hIREFCT0ZPTUVDGAcgASgFQh6qAhtFZ2dMaW5rLkRhbmhlbmdTZXJ2ZXIu",
            "UHJvdG9iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::EggLink.DanhengServer.Proto.EBOIOIKFLFJReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EggLink.DanhengServer.Proto.ChessRogueGameAeonInfo), global::EggLink.DanhengServer.Proto.ChessRogueGameAeonInfo.Parser, new[]{ "GameAeonId", "OAKNGNKALPI", "HHDABOFOMEC" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ChessRogueGameAeonInfo : pb::IMessage<ChessRogueGameAeonInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ChessRogueGameAeonInfo> _parser = new pb::MessageParser<ChessRogueGameAeonInfo>(() => new ChessRogueGameAeonInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ChessRogueGameAeonInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EggLink.DanhengServer.Proto.ChessRogueGameAeonInfoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ChessRogueGameAeonInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ChessRogueGameAeonInfo(ChessRogueGameAeonInfo other) : this() {
      gameAeonId_ = other.gameAeonId_;
      oAKNGNKALPI_ = other.oAKNGNKALPI_ != null ? other.oAKNGNKALPI_.Clone() : null;
      hHDABOFOMEC_ = other.hHDABOFOMEC_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ChessRogueGameAeonInfo Clone() {
      return new ChessRogueGameAeonInfo(this);
    }

    /// <summary>Field number for the "game_aeon_id" field.</summary>
    public const int GameAeonIdFieldNumber = 14;
    private uint gameAeonId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint GameAeonId {
      get { return gameAeonId_; }
      set {
        gameAeonId_ = value;
      }
    }

    /// <summary>Field number for the "OAKNGNKALPI" field.</summary>
    public const int OAKNGNKALPIFieldNumber = 3;
    private global::EggLink.DanhengServer.Proto.EBOIOIKFLFJ oAKNGNKALPI_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::EggLink.DanhengServer.Proto.EBOIOIKFLFJ OAKNGNKALPI {
      get { return oAKNGNKALPI_; }
      set {
        oAKNGNKALPI_ = value;
      }
    }

    /// <summary>Field number for the "HHDABOFOMEC" field.</summary>
    public const int HHDABOFOMECFieldNumber = 7;
    private int hHDABOFOMEC_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int HHDABOFOMEC {
      get { return hHDABOFOMEC_; }
      set {
        hHDABOFOMEC_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ChessRogueGameAeonInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ChessRogueGameAeonInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (GameAeonId != other.GameAeonId) return false;
      if (!object.Equals(OAKNGNKALPI, other.OAKNGNKALPI)) return false;
      if (HHDABOFOMEC != other.HHDABOFOMEC) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (GameAeonId != 0) hash ^= GameAeonId.GetHashCode();
      if (oAKNGNKALPI_ != null) hash ^= OAKNGNKALPI.GetHashCode();
      if (HHDABOFOMEC != 0) hash ^= HHDABOFOMEC.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (oAKNGNKALPI_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(OAKNGNKALPI);
      }
      if (HHDABOFOMEC != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(HHDABOFOMEC);
      }
      if (GameAeonId != 0) {
        output.WriteRawTag(112);
        output.WriteUInt32(GameAeonId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (oAKNGNKALPI_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(OAKNGNKALPI);
      }
      if (HHDABOFOMEC != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(HHDABOFOMEC);
      }
      if (GameAeonId != 0) {
        output.WriteRawTag(112);
        output.WriteUInt32(GameAeonId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (GameAeonId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(GameAeonId);
      }
      if (oAKNGNKALPI_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(OAKNGNKALPI);
      }
      if (HHDABOFOMEC != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(HHDABOFOMEC);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ChessRogueGameAeonInfo other) {
      if (other == null) {
        return;
      }
      if (other.GameAeonId != 0) {
        GameAeonId = other.GameAeonId;
      }
      if (other.oAKNGNKALPI_ != null) {
        if (oAKNGNKALPI_ == null) {
          OAKNGNKALPI = new global::EggLink.DanhengServer.Proto.EBOIOIKFLFJ();
        }
        OAKNGNKALPI.MergeFrom(other.OAKNGNKALPI);
      }
      if (other.HHDABOFOMEC != 0) {
        HHDABOFOMEC = other.HHDABOFOMEC;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 26: {
            if (oAKNGNKALPI_ == null) {
              OAKNGNKALPI = new global::EggLink.DanhengServer.Proto.EBOIOIKFLFJ();
            }
            input.ReadMessage(OAKNGNKALPI);
            break;
          }
          case 56: {
            HHDABOFOMEC = input.ReadInt32();
            break;
          }
          case 112: {
            GameAeonId = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 26: {
            if (oAKNGNKALPI_ == null) {
              OAKNGNKALPI = new global::EggLink.DanhengServer.Proto.EBOIOIKFLFJ();
            }
            input.ReadMessage(OAKNGNKALPI);
            break;
          }
          case 56: {
            HHDABOFOMEC = input.ReadInt32();
            break;
          }
          case 112: {
            GameAeonId = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
