// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: DKOCAAOHIBK.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from DKOCAAOHIBK.proto</summary>
  public static partial class DKOCAAOHIBKReflection {

    #region Descriptor
    /// <summary>File descriptor for DKOCAAOHIBK.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DKOCAAOHIBKReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFES09DQUFPSElCSy5wcm90bxoRUEFITElNQ0pCRUIucHJvdG8i7gEKC0RL",
            "T0NBQU9ISUJLEhMKC1BEREZLQUVMSE1QGA0gASgNEhQKDGNoYWxsZW5nZV9p",
            "ZBgBIAEoDRITCgtCSUlESkdESUVKRBgMIAEoDRITCgthdmF0YXJfbGlzdBgJ",
            "IAMoDRITCgtGRUhKSUJJTERNTRgPIAEoDRITCgtHS0ZJQkFFT0hFTRgHIAMo",
            "DRITCgtOSU9ETUlEQ0lJTRgIIAEoCBITCgtJRkVGR0RORktOTxgFIAEoDRIT",
            "CgtGSkRNQkpLRENLSRgEIAEoDRIhCgtMSUlBTURHS1BBRhgGIAMoCzIMLlBB",
            "SExJTUNKQkVCQh6qAhtFZ2dMaW5rLkRhbmhlbmdTZXJ2ZXIuUHJvdG9iBnBy",
            "b3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::EggLink.DanhengServer.Proto.PAHLIMCJBEBReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EggLink.DanhengServer.Proto.DKOCAAOHIBK), global::EggLink.DanhengServer.Proto.DKOCAAOHIBK.Parser, new[]{ "PDDFKAELHMP", "ChallengeId", "BIIDJGDIEJD", "AvatarList", "FEHJIBILDMM", "GKFIBAEOHEM", "NIODMIDCIIM", "IFEFGDNFKNO", "FJDMBJKDCKI", "LIIAMDGKPAF" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class DKOCAAOHIBK : pb::IMessage<DKOCAAOHIBK>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DKOCAAOHIBK> _parser = new pb::MessageParser<DKOCAAOHIBK>(() => new DKOCAAOHIBK());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<DKOCAAOHIBK> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EggLink.DanhengServer.Proto.DKOCAAOHIBKReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DKOCAAOHIBK() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DKOCAAOHIBK(DKOCAAOHIBK other) : this() {
      pDDFKAELHMP_ = other.pDDFKAELHMP_;
      challengeId_ = other.challengeId_;
      bIIDJGDIEJD_ = other.bIIDJGDIEJD_;
      avatarList_ = other.avatarList_.Clone();
      fEHJIBILDMM_ = other.fEHJIBILDMM_;
      gKFIBAEOHEM_ = other.gKFIBAEOHEM_.Clone();
      nIODMIDCIIM_ = other.nIODMIDCIIM_;
      iFEFGDNFKNO_ = other.iFEFGDNFKNO_;
      fJDMBJKDCKI_ = other.fJDMBJKDCKI_;
      lIIAMDGKPAF_ = other.lIIAMDGKPAF_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DKOCAAOHIBK Clone() {
      return new DKOCAAOHIBK(this);
    }

    /// <summary>Field number for the "PDDFKAELHMP" field.</summary>
    public const int PDDFKAELHMPFieldNumber = 13;
    private uint pDDFKAELHMP_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint PDDFKAELHMP {
      get { return pDDFKAELHMP_; }
      set {
        pDDFKAELHMP_ = value;
      }
    }

    /// <summary>Field number for the "challenge_id" field.</summary>
    public const int ChallengeIdFieldNumber = 1;
    private uint challengeId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint ChallengeId {
      get { return challengeId_; }
      set {
        challengeId_ = value;
      }
    }

    /// <summary>Field number for the "BIIDJGDIEJD" field.</summary>
    public const int BIIDJGDIEJDFieldNumber = 12;
    private uint bIIDJGDIEJD_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint BIIDJGDIEJD {
      get { return bIIDJGDIEJD_; }
      set {
        bIIDJGDIEJD_ = value;
      }
    }

    /// <summary>Field number for the "avatar_list" field.</summary>
    public const int AvatarListFieldNumber = 9;
    private static readonly pb::FieldCodec<uint> _repeated_avatarList_codec
        = pb::FieldCodec.ForUInt32(74);
    private readonly pbc::RepeatedField<uint> avatarList_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> AvatarList {
      get { return avatarList_; }
    }

    /// <summary>Field number for the "FEHJIBILDMM" field.</summary>
    public const int FEHJIBILDMMFieldNumber = 15;
    private uint fEHJIBILDMM_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint FEHJIBILDMM {
      get { return fEHJIBILDMM_; }
      set {
        fEHJIBILDMM_ = value;
      }
    }

    /// <summary>Field number for the "GKFIBAEOHEM" field.</summary>
    public const int GKFIBAEOHEMFieldNumber = 7;
    private static readonly pb::FieldCodec<uint> _repeated_gKFIBAEOHEM_codec
        = pb::FieldCodec.ForUInt32(58);
    private readonly pbc::RepeatedField<uint> gKFIBAEOHEM_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> GKFIBAEOHEM {
      get { return gKFIBAEOHEM_; }
    }

    /// <summary>Field number for the "NIODMIDCIIM" field.</summary>
    public const int NIODMIDCIIMFieldNumber = 8;
    private bool nIODMIDCIIM_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool NIODMIDCIIM {
      get { return nIODMIDCIIM_; }
      set {
        nIODMIDCIIM_ = value;
      }
    }

    /// <summary>Field number for the "IFEFGDNFKNO" field.</summary>
    public const int IFEFGDNFKNOFieldNumber = 5;
    private uint iFEFGDNFKNO_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint IFEFGDNFKNO {
      get { return iFEFGDNFKNO_; }
      set {
        iFEFGDNFKNO_ = value;
      }
    }

    /// <summary>Field number for the "FJDMBJKDCKI" field.</summary>
    public const int FJDMBJKDCKIFieldNumber = 4;
    private uint fJDMBJKDCKI_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint FJDMBJKDCKI {
      get { return fJDMBJKDCKI_; }
      set {
        fJDMBJKDCKI_ = value;
      }
    }

    /// <summary>Field number for the "LIIAMDGKPAF" field.</summary>
    public const int LIIAMDGKPAFFieldNumber = 6;
    private static readonly pb::FieldCodec<global::EggLink.DanhengServer.Proto.PAHLIMCJBEB> _repeated_lIIAMDGKPAF_codec
        = pb::FieldCodec.ForMessage(50, global::EggLink.DanhengServer.Proto.PAHLIMCJBEB.Parser);
    private readonly pbc::RepeatedField<global::EggLink.DanhengServer.Proto.PAHLIMCJBEB> lIIAMDGKPAF_ = new pbc::RepeatedField<global::EggLink.DanhengServer.Proto.PAHLIMCJBEB>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::EggLink.DanhengServer.Proto.PAHLIMCJBEB> LIIAMDGKPAF {
      get { return lIIAMDGKPAF_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as DKOCAAOHIBK);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(DKOCAAOHIBK other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PDDFKAELHMP != other.PDDFKAELHMP) return false;
      if (ChallengeId != other.ChallengeId) return false;
      if (BIIDJGDIEJD != other.BIIDJGDIEJD) return false;
      if(!avatarList_.Equals(other.avatarList_)) return false;
      if (FEHJIBILDMM != other.FEHJIBILDMM) return false;
      if(!gKFIBAEOHEM_.Equals(other.gKFIBAEOHEM_)) return false;
      if (NIODMIDCIIM != other.NIODMIDCIIM) return false;
      if (IFEFGDNFKNO != other.IFEFGDNFKNO) return false;
      if (FJDMBJKDCKI != other.FJDMBJKDCKI) return false;
      if(!lIIAMDGKPAF_.Equals(other.lIIAMDGKPAF_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (PDDFKAELHMP != 0) hash ^= PDDFKAELHMP.GetHashCode();
      if (ChallengeId != 0) hash ^= ChallengeId.GetHashCode();
      if (BIIDJGDIEJD != 0) hash ^= BIIDJGDIEJD.GetHashCode();
      hash ^= avatarList_.GetHashCode();
      if (FEHJIBILDMM != 0) hash ^= FEHJIBILDMM.GetHashCode();
      hash ^= gKFIBAEOHEM_.GetHashCode();
      if (NIODMIDCIIM != false) hash ^= NIODMIDCIIM.GetHashCode();
      if (IFEFGDNFKNO != 0) hash ^= IFEFGDNFKNO.GetHashCode();
      if (FJDMBJKDCKI != 0) hash ^= FJDMBJKDCKI.GetHashCode();
      hash ^= lIIAMDGKPAF_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ChallengeId != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(ChallengeId);
      }
      if (FJDMBJKDCKI != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(FJDMBJKDCKI);
      }
      if (IFEFGDNFKNO != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(IFEFGDNFKNO);
      }
      lIIAMDGKPAF_.WriteTo(output, _repeated_lIIAMDGKPAF_codec);
      gKFIBAEOHEM_.WriteTo(output, _repeated_gKFIBAEOHEM_codec);
      if (NIODMIDCIIM != false) {
        output.WriteRawTag(64);
        output.WriteBool(NIODMIDCIIM);
      }
      avatarList_.WriteTo(output, _repeated_avatarList_codec);
      if (BIIDJGDIEJD != 0) {
        output.WriteRawTag(96);
        output.WriteUInt32(BIIDJGDIEJD);
      }
      if (PDDFKAELHMP != 0) {
        output.WriteRawTag(104);
        output.WriteUInt32(PDDFKAELHMP);
      }
      if (FEHJIBILDMM != 0) {
        output.WriteRawTag(120);
        output.WriteUInt32(FEHJIBILDMM);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ChallengeId != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(ChallengeId);
      }
      if (FJDMBJKDCKI != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(FJDMBJKDCKI);
      }
      if (IFEFGDNFKNO != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(IFEFGDNFKNO);
      }
      lIIAMDGKPAF_.WriteTo(ref output, _repeated_lIIAMDGKPAF_codec);
      gKFIBAEOHEM_.WriteTo(ref output, _repeated_gKFIBAEOHEM_codec);
      if (NIODMIDCIIM != false) {
        output.WriteRawTag(64);
        output.WriteBool(NIODMIDCIIM);
      }
      avatarList_.WriteTo(ref output, _repeated_avatarList_codec);
      if (BIIDJGDIEJD != 0) {
        output.WriteRawTag(96);
        output.WriteUInt32(BIIDJGDIEJD);
      }
      if (PDDFKAELHMP != 0) {
        output.WriteRawTag(104);
        output.WriteUInt32(PDDFKAELHMP);
      }
      if (FEHJIBILDMM != 0) {
        output.WriteRawTag(120);
        output.WriteUInt32(FEHJIBILDMM);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (PDDFKAELHMP != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(PDDFKAELHMP);
      }
      if (ChallengeId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ChallengeId);
      }
      if (BIIDJGDIEJD != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(BIIDJGDIEJD);
      }
      size += avatarList_.CalculateSize(_repeated_avatarList_codec);
      if (FEHJIBILDMM != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(FEHJIBILDMM);
      }
      size += gKFIBAEOHEM_.CalculateSize(_repeated_gKFIBAEOHEM_codec);
      if (NIODMIDCIIM != false) {
        size += 1 + 1;
      }
      if (IFEFGDNFKNO != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(IFEFGDNFKNO);
      }
      if (FJDMBJKDCKI != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(FJDMBJKDCKI);
      }
      size += lIIAMDGKPAF_.CalculateSize(_repeated_lIIAMDGKPAF_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(DKOCAAOHIBK other) {
      if (other == null) {
        return;
      }
      if (other.PDDFKAELHMP != 0) {
        PDDFKAELHMP = other.PDDFKAELHMP;
      }
      if (other.ChallengeId != 0) {
        ChallengeId = other.ChallengeId;
      }
      if (other.BIIDJGDIEJD != 0) {
        BIIDJGDIEJD = other.BIIDJGDIEJD;
      }
      avatarList_.Add(other.avatarList_);
      if (other.FEHJIBILDMM != 0) {
        FEHJIBILDMM = other.FEHJIBILDMM;
      }
      gKFIBAEOHEM_.Add(other.gKFIBAEOHEM_);
      if (other.NIODMIDCIIM != false) {
        NIODMIDCIIM = other.NIODMIDCIIM;
      }
      if (other.IFEFGDNFKNO != 0) {
        IFEFGDNFKNO = other.IFEFGDNFKNO;
      }
      if (other.FJDMBJKDCKI != 0) {
        FJDMBJKDCKI = other.FJDMBJKDCKI;
      }
      lIIAMDGKPAF_.Add(other.lIIAMDGKPAF_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ChallengeId = input.ReadUInt32();
            break;
          }
          case 32: {
            FJDMBJKDCKI = input.ReadUInt32();
            break;
          }
          case 40: {
            IFEFGDNFKNO = input.ReadUInt32();
            break;
          }
          case 50: {
            lIIAMDGKPAF_.AddEntriesFrom(input, _repeated_lIIAMDGKPAF_codec);
            break;
          }
          case 58:
          case 56: {
            gKFIBAEOHEM_.AddEntriesFrom(input, _repeated_gKFIBAEOHEM_codec);
            break;
          }
          case 64: {
            NIODMIDCIIM = input.ReadBool();
            break;
          }
          case 74:
          case 72: {
            avatarList_.AddEntriesFrom(input, _repeated_avatarList_codec);
            break;
          }
          case 96: {
            BIIDJGDIEJD = input.ReadUInt32();
            break;
          }
          case 104: {
            PDDFKAELHMP = input.ReadUInt32();
            break;
          }
          case 120: {
            FEHJIBILDMM = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ChallengeId = input.ReadUInt32();
            break;
          }
          case 32: {
            FJDMBJKDCKI = input.ReadUInt32();
            break;
          }
          case 40: {
            IFEFGDNFKNO = input.ReadUInt32();
            break;
          }
          case 50: {
            lIIAMDGKPAF_.AddEntriesFrom(ref input, _repeated_lIIAMDGKPAF_codec);
            break;
          }
          case 58:
          case 56: {
            gKFIBAEOHEM_.AddEntriesFrom(ref input, _repeated_gKFIBAEOHEM_codec);
            break;
          }
          case 64: {
            NIODMIDCIIM = input.ReadBool();
            break;
          }
          case 74:
          case 72: {
            avatarList_.AddEntriesFrom(ref input, _repeated_avatarList_codec);
            break;
          }
          case 96: {
            BIIDJGDIEJD = input.ReadUInt32();
            break;
          }
          case 104: {
            PDDFKAELHMP = input.ReadUInt32();
            break;
          }
          case 120: {
            FEHJIBILDMM = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
