// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: GEANJPFCADJ.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from GEANJPFCADJ.proto</summary>
  public static partial class GEANJPFCADJReflection {

    #region Descriptor
    /// <summary>File descriptor for GEANJPFCADJ.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GEANJPFCADJReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFHRUFOSlBGQ0FESi5wcm90byJGCgtHRUFOSlBGQ0FEShITCgtFSkxFREFK",
            "SkRESBgKIAEoDRINCgVsZXZlbBgCIAEoDRITCgtNSUpHS05QTUlETBgMIAEo",
            "DUIeqgIbRWdnTGluay5EYW5oZW5nU2VydmVyLlByb3RvYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EggLink.DanhengServer.Proto.GEANJPFCADJ), global::EggLink.DanhengServer.Proto.GEANJPFCADJ.Parser, new[]{ "EJLEDAJJDDH", "Level", "MIJGKNPMIDL" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class GEANJPFCADJ : pb::IMessage<GEANJPFCADJ>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GEANJPFCADJ> _parser = new pb::MessageParser<GEANJPFCADJ>(() => new GEANJPFCADJ());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GEANJPFCADJ> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EggLink.DanhengServer.Proto.GEANJPFCADJReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GEANJPFCADJ() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GEANJPFCADJ(GEANJPFCADJ other) : this() {
      eJLEDAJJDDH_ = other.eJLEDAJJDDH_;
      level_ = other.level_;
      mIJGKNPMIDL_ = other.mIJGKNPMIDL_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GEANJPFCADJ Clone() {
      return new GEANJPFCADJ(this);
    }

    /// <summary>Field number for the "EJLEDAJJDDH" field.</summary>
    public const int EJLEDAJJDDHFieldNumber = 10;
    private uint eJLEDAJJDDH_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint EJLEDAJJDDH {
      get { return eJLEDAJJDDH_; }
      set {
        eJLEDAJJDDH_ = value;
      }
    }

    /// <summary>Field number for the "level" field.</summary>
    public const int LevelFieldNumber = 2;
    private uint level_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Level {
      get { return level_; }
      set {
        level_ = value;
      }
    }

    /// <summary>Field number for the "MIJGKNPMIDL" field.</summary>
    public const int MIJGKNPMIDLFieldNumber = 12;
    private uint mIJGKNPMIDL_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint MIJGKNPMIDL {
      get { return mIJGKNPMIDL_; }
      set {
        mIJGKNPMIDL_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GEANJPFCADJ);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GEANJPFCADJ other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (EJLEDAJJDDH != other.EJLEDAJJDDH) return false;
      if (Level != other.Level) return false;
      if (MIJGKNPMIDL != other.MIJGKNPMIDL) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (EJLEDAJJDDH != 0) hash ^= EJLEDAJJDDH.GetHashCode();
      if (Level != 0) hash ^= Level.GetHashCode();
      if (MIJGKNPMIDL != 0) hash ^= MIJGKNPMIDL.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Level != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Level);
      }
      if (EJLEDAJJDDH != 0) {
        output.WriteRawTag(80);
        output.WriteUInt32(EJLEDAJJDDH);
      }
      if (MIJGKNPMIDL != 0) {
        output.WriteRawTag(96);
        output.WriteUInt32(MIJGKNPMIDL);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Level != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Level);
      }
      if (EJLEDAJJDDH != 0) {
        output.WriteRawTag(80);
        output.WriteUInt32(EJLEDAJJDDH);
      }
      if (MIJGKNPMIDL != 0) {
        output.WriteRawTag(96);
        output.WriteUInt32(MIJGKNPMIDL);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (EJLEDAJJDDH != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(EJLEDAJJDDH);
      }
      if (Level != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Level);
      }
      if (MIJGKNPMIDL != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MIJGKNPMIDL);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GEANJPFCADJ other) {
      if (other == null) {
        return;
      }
      if (other.EJLEDAJJDDH != 0) {
        EJLEDAJJDDH = other.EJLEDAJJDDH;
      }
      if (other.Level != 0) {
        Level = other.Level;
      }
      if (other.MIJGKNPMIDL != 0) {
        MIJGKNPMIDL = other.MIJGKNPMIDL;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 16: {
            Level = input.ReadUInt32();
            break;
          }
          case 80: {
            EJLEDAJJDDH = input.ReadUInt32();
            break;
          }
          case 96: {
            MIJGKNPMIDL = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 16: {
            Level = input.ReadUInt32();
            break;
          }
          case 80: {
            EJLEDAJJDDH = input.ReadUInt32();
            break;
          }
          case 96: {
            MIJGKNPMIDL = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
