// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: MEDPAMLOEMC.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from MEDPAMLOEMC.proto</summary>
  public static partial class MEDPAMLOEMCReflection {

    #region Descriptor
    /// <summary>File descriptor for MEDPAMLOEMC.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MEDPAMLOEMCReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFNRURQQU1MT0VNQy5wcm90byKfAQoLTUVEUEFNTE9FTUMSEwoLRkxFQ0lH",
            "TE1GRFAYDSABKA0SEwoLS0RDSkdGQU5KREcYAiABKA0SMgoLRUxETkNHRUFM",
            "S0kYDiADKAsyHS5NRURQQU1MT0VNQy5FTEROQ0dFQUxLSUVudHJ5GjIKEEVM",
            "RE5DR0VBTEtJRW50cnkSCwoDa2V5GAEgASgNEg0KBXZhbHVlGAIgASgNOgI4",
            "AUIeqgIbRWdnTGluay5EYW5oZW5nU2VydmVyLlByb3RvYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EggLink.DanhengServer.Proto.MEDPAMLOEMC), global::EggLink.DanhengServer.Proto.MEDPAMLOEMC.Parser, new[]{ "FLECIGLMFDP", "KDCJGFANJDG", "ELDNCGEALKI" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, })
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class MEDPAMLOEMC : pb::IMessage<MEDPAMLOEMC>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MEDPAMLOEMC> _parser = new pb::MessageParser<MEDPAMLOEMC>(() => new MEDPAMLOEMC());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MEDPAMLOEMC> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EggLink.DanhengServer.Proto.MEDPAMLOEMCReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MEDPAMLOEMC() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MEDPAMLOEMC(MEDPAMLOEMC other) : this() {
      fLECIGLMFDP_ = other.fLECIGLMFDP_;
      kDCJGFANJDG_ = other.kDCJGFANJDG_;
      eLDNCGEALKI_ = other.eLDNCGEALKI_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MEDPAMLOEMC Clone() {
      return new MEDPAMLOEMC(this);
    }

    /// <summary>Field number for the "FLECIGLMFDP" field.</summary>
    public const int FLECIGLMFDPFieldNumber = 13;
    private uint fLECIGLMFDP_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint FLECIGLMFDP {
      get { return fLECIGLMFDP_; }
      set {
        fLECIGLMFDP_ = value;
      }
    }

    /// <summary>Field number for the "KDCJGFANJDG" field.</summary>
    public const int KDCJGFANJDGFieldNumber = 2;
    private uint kDCJGFANJDG_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint KDCJGFANJDG {
      get { return kDCJGFANJDG_; }
      set {
        kDCJGFANJDG_ = value;
      }
    }

    /// <summary>Field number for the "ELDNCGEALKI" field.</summary>
    public const int ELDNCGEALKIFieldNumber = 14;
    private static readonly pbc::MapField<uint, uint>.Codec _map_eLDNCGEALKI_codec
        = new pbc::MapField<uint, uint>.Codec(pb::FieldCodec.ForUInt32(8, 0), pb::FieldCodec.ForUInt32(16, 0), 114);
    private readonly pbc::MapField<uint, uint> eLDNCGEALKI_ = new pbc::MapField<uint, uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<uint, uint> ELDNCGEALKI {
      get { return eLDNCGEALKI_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MEDPAMLOEMC);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MEDPAMLOEMC other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (FLECIGLMFDP != other.FLECIGLMFDP) return false;
      if (KDCJGFANJDG != other.KDCJGFANJDG) return false;
      if (!ELDNCGEALKI.Equals(other.ELDNCGEALKI)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (FLECIGLMFDP != 0) hash ^= FLECIGLMFDP.GetHashCode();
      if (KDCJGFANJDG != 0) hash ^= KDCJGFANJDG.GetHashCode();
      hash ^= ELDNCGEALKI.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (KDCJGFANJDG != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(KDCJGFANJDG);
      }
      if (FLECIGLMFDP != 0) {
        output.WriteRawTag(104);
        output.WriteUInt32(FLECIGLMFDP);
      }
      eLDNCGEALKI_.WriteTo(output, _map_eLDNCGEALKI_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (KDCJGFANJDG != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(KDCJGFANJDG);
      }
      if (FLECIGLMFDP != 0) {
        output.WriteRawTag(104);
        output.WriteUInt32(FLECIGLMFDP);
      }
      eLDNCGEALKI_.WriteTo(ref output, _map_eLDNCGEALKI_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (FLECIGLMFDP != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(FLECIGLMFDP);
      }
      if (KDCJGFANJDG != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(KDCJGFANJDG);
      }
      size += eLDNCGEALKI_.CalculateSize(_map_eLDNCGEALKI_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MEDPAMLOEMC other) {
      if (other == null) {
        return;
      }
      if (other.FLECIGLMFDP != 0) {
        FLECIGLMFDP = other.FLECIGLMFDP;
      }
      if (other.KDCJGFANJDG != 0) {
        KDCJGFANJDG = other.KDCJGFANJDG;
      }
      eLDNCGEALKI_.MergeFrom(other.eLDNCGEALKI_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 16: {
            KDCJGFANJDG = input.ReadUInt32();
            break;
          }
          case 104: {
            FLECIGLMFDP = input.ReadUInt32();
            break;
          }
          case 114: {
            eLDNCGEALKI_.AddEntriesFrom(input, _map_eLDNCGEALKI_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 16: {
            KDCJGFANJDG = input.ReadUInt32();
            break;
          }
          case 104: {
            FLECIGLMFDP = input.ReadUInt32();
            break;
          }
          case 114: {
            eLDNCGEALKI_.AddEntriesFrom(ref input, _map_eLDNCGEALKI_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
