// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: MissionEventSync.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from MissionEventSync.proto</summary>
  public static partial class MissionEventSyncReflection {

    #region Descriptor
    /// <summary>File descriptor for MissionEventSync.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MissionEventSyncReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZNaXNzaW9uRXZlbnRTeW5jLnByb3RvGg1NaXNzaW9uLnByb3RvIoMBChBN",
            "aXNzaW9uRXZlbnRTeW5jEiEKGWRlbF9taXNzaW9uX2V2ZW50X2lkX2xpc3QY",
            "ASADKA0SJgoeZmluaXNoZWRfbWlzc2lvbl9ldmVudF9pZF9saXN0GAogAygN",
            "EiQKEm1pc3Npb25fZXZlbnRfbGlzdBgFIAMoCzIILk1pc3Npb25CHqoCG0Vn",
            "Z0xpbmsuRGFuaGVuZ1NlcnZlci5Qcm90b2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::EggLink.DanhengServer.Proto.MissionReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EggLink.DanhengServer.Proto.MissionEventSync), global::EggLink.DanhengServer.Proto.MissionEventSync.Parser, new[]{ "DelMissionEventIdList", "FinishedMissionEventIdList", "MissionEventList" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class MissionEventSync : pb::IMessage<MissionEventSync>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MissionEventSync> _parser = new pb::MessageParser<MissionEventSync>(() => new MissionEventSync());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MissionEventSync> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EggLink.DanhengServer.Proto.MissionEventSyncReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MissionEventSync() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MissionEventSync(MissionEventSync other) : this() {
      delMissionEventIdList_ = other.delMissionEventIdList_.Clone();
      finishedMissionEventIdList_ = other.finishedMissionEventIdList_.Clone();
      missionEventList_ = other.missionEventList_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MissionEventSync Clone() {
      return new MissionEventSync(this);
    }

    /// <summary>Field number for the "del_mission_event_id_list" field.</summary>
    public const int DelMissionEventIdListFieldNumber = 1;
    private static readonly pb::FieldCodec<uint> _repeated_delMissionEventIdList_codec
        = pb::FieldCodec.ForUInt32(10);
    private readonly pbc::RepeatedField<uint> delMissionEventIdList_ = new pbc::RepeatedField<uint>();
    /// <summary>
    /// 10
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> DelMissionEventIdList {
      get { return delMissionEventIdList_; }
    }

    /// <summary>Field number for the "finished_mission_event_id_list" field.</summary>
    public const int FinishedMissionEventIdListFieldNumber = 10;
    private static readonly pb::FieldCodec<uint> _repeated_finishedMissionEventIdList_codec
        = pb::FieldCodec.ForUInt32(82);
    private readonly pbc::RepeatedField<uint> finishedMissionEventIdList_ = new pbc::RepeatedField<uint>();
    /// <summary>
    /// 1
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> FinishedMissionEventIdList {
      get { return finishedMissionEventIdList_; }
    }

    /// <summary>Field number for the "mission_event_list" field.</summary>
    public const int MissionEventListFieldNumber = 5;
    private static readonly pb::FieldCodec<global::EggLink.DanhengServer.Proto.Mission> _repeated_missionEventList_codec
        = pb::FieldCodec.ForMessage(42, global::EggLink.DanhengServer.Proto.Mission.Parser);
    private readonly pbc::RepeatedField<global::EggLink.DanhengServer.Proto.Mission> missionEventList_ = new pbc::RepeatedField<global::EggLink.DanhengServer.Proto.Mission>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::EggLink.DanhengServer.Proto.Mission> MissionEventList {
      get { return missionEventList_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MissionEventSync);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MissionEventSync other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!delMissionEventIdList_.Equals(other.delMissionEventIdList_)) return false;
      if(!finishedMissionEventIdList_.Equals(other.finishedMissionEventIdList_)) return false;
      if(!missionEventList_.Equals(other.missionEventList_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= delMissionEventIdList_.GetHashCode();
      hash ^= finishedMissionEventIdList_.GetHashCode();
      hash ^= missionEventList_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      delMissionEventIdList_.WriteTo(output, _repeated_delMissionEventIdList_codec);
      missionEventList_.WriteTo(output, _repeated_missionEventList_codec);
      finishedMissionEventIdList_.WriteTo(output, _repeated_finishedMissionEventIdList_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      delMissionEventIdList_.WriteTo(ref output, _repeated_delMissionEventIdList_codec);
      missionEventList_.WriteTo(ref output, _repeated_missionEventList_codec);
      finishedMissionEventIdList_.WriteTo(ref output, _repeated_finishedMissionEventIdList_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += delMissionEventIdList_.CalculateSize(_repeated_delMissionEventIdList_codec);
      size += finishedMissionEventIdList_.CalculateSize(_repeated_finishedMissionEventIdList_codec);
      size += missionEventList_.CalculateSize(_repeated_missionEventList_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MissionEventSync other) {
      if (other == null) {
        return;
      }
      delMissionEventIdList_.Add(other.delMissionEventIdList_);
      finishedMissionEventIdList_.Add(other.finishedMissionEventIdList_);
      missionEventList_.Add(other.missionEventList_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10:
          case 8: {
            delMissionEventIdList_.AddEntriesFrom(input, _repeated_delMissionEventIdList_codec);
            break;
          }
          case 42: {
            missionEventList_.AddEntriesFrom(input, _repeated_missionEventList_codec);
            break;
          }
          case 82:
          case 80: {
            finishedMissionEventIdList_.AddEntriesFrom(input, _repeated_finishedMissionEventIdList_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10:
          case 8: {
            delMissionEventIdList_.AddEntriesFrom(ref input, _repeated_delMissionEventIdList_codec);
            break;
          }
          case 42: {
            missionEventList_.AddEntriesFrom(ref input, _repeated_missionEventList_codec);
            break;
          }
          case 82:
          case 80: {
            finishedMissionEventIdList_.AddEntriesFrom(ref input, _repeated_finishedMissionEventIdList_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
