// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: RogueEndlessLayerInfo.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from RogueEndlessLayerInfo.proto</summary>
  public static partial class RogueEndlessLayerInfoReflection {

    #region Descriptor
    /// <summary>File descriptor for RogueEndlessLayerInfo.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static RogueEndlessLayerInfoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChtSb2d1ZUVuZGxlc3NMYXllckluZm8ucHJvdG8iwQEKFVJvZ3VlRW5kbGVz",
            "c0xheWVySW5mbxIXCg90dXJuX2xlZnRfY291bnQYBSABKA0SEwoLS05OTkdM",
            "RUFKRkkYAyABKA0SEwoLSElFSUxQTU5FSEoYCiABKA0SEwoLSEtLTEtFTEdO",
            "RkgYDiABKA0SEQoJYmF0dGxlX2lkGAYgASgNEhMKC0hHSE5JSE9GS09FGAcg",
            "ASgNEhMKC0pFQkZHTk1HRk5CGA0gASgIEhMKC0NFTE9OS0JGS0JKGAEgASgN",
            "Qh6qAhtFZ2dMaW5rLkRhbmhlbmdTZXJ2ZXIuUHJvdG9iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EggLink.DanhengServer.Proto.RogueEndlessLayerInfo), global::EggLink.DanhengServer.Proto.RogueEndlessLayerInfo.Parser, new[]{ "TurnLeftCount", "KNNNGLEAJFI", "HIEILPMNEHJ", "HKKLKELGNFH", "BattleId", "HGHNIHOFKOE", "JEBFGNMGFNB", "CELONKBFKBJ" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class RogueEndlessLayerInfo : pb::IMessage<RogueEndlessLayerInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RogueEndlessLayerInfo> _parser = new pb::MessageParser<RogueEndlessLayerInfo>(() => new RogueEndlessLayerInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RogueEndlessLayerInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EggLink.DanhengServer.Proto.RogueEndlessLayerInfoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RogueEndlessLayerInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RogueEndlessLayerInfo(RogueEndlessLayerInfo other) : this() {
      turnLeftCount_ = other.turnLeftCount_;
      kNNNGLEAJFI_ = other.kNNNGLEAJFI_;
      hIEILPMNEHJ_ = other.hIEILPMNEHJ_;
      hKKLKELGNFH_ = other.hKKLKELGNFH_;
      battleId_ = other.battleId_;
      hGHNIHOFKOE_ = other.hGHNIHOFKOE_;
      jEBFGNMGFNB_ = other.jEBFGNMGFNB_;
      cELONKBFKBJ_ = other.cELONKBFKBJ_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RogueEndlessLayerInfo Clone() {
      return new RogueEndlessLayerInfo(this);
    }

    /// <summary>Field number for the "turn_left_count" field.</summary>
    public const int TurnLeftCountFieldNumber = 5;
    private uint turnLeftCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint TurnLeftCount {
      get { return turnLeftCount_; }
      set {
        turnLeftCount_ = value;
      }
    }

    /// <summary>Field number for the "KNNNGLEAJFI" field.</summary>
    public const int KNNNGLEAJFIFieldNumber = 3;
    private uint kNNNGLEAJFI_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint KNNNGLEAJFI {
      get { return kNNNGLEAJFI_; }
      set {
        kNNNGLEAJFI_ = value;
      }
    }

    /// <summary>Field number for the "HIEILPMNEHJ" field.</summary>
    public const int HIEILPMNEHJFieldNumber = 10;
    private uint hIEILPMNEHJ_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint HIEILPMNEHJ {
      get { return hIEILPMNEHJ_; }
      set {
        hIEILPMNEHJ_ = value;
      }
    }

    /// <summary>Field number for the "HKKLKELGNFH" field.</summary>
    public const int HKKLKELGNFHFieldNumber = 14;
    private uint hKKLKELGNFH_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint HKKLKELGNFH {
      get { return hKKLKELGNFH_; }
      set {
        hKKLKELGNFH_ = value;
      }
    }

    /// <summary>Field number for the "battle_id" field.</summary>
    public const int BattleIdFieldNumber = 6;
    private uint battleId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint BattleId {
      get { return battleId_; }
      set {
        battleId_ = value;
      }
    }

    /// <summary>Field number for the "HGHNIHOFKOE" field.</summary>
    public const int HGHNIHOFKOEFieldNumber = 7;
    private uint hGHNIHOFKOE_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint HGHNIHOFKOE {
      get { return hGHNIHOFKOE_; }
      set {
        hGHNIHOFKOE_ = value;
      }
    }

    /// <summary>Field number for the "JEBFGNMGFNB" field.</summary>
    public const int JEBFGNMGFNBFieldNumber = 13;
    private bool jEBFGNMGFNB_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool JEBFGNMGFNB {
      get { return jEBFGNMGFNB_; }
      set {
        jEBFGNMGFNB_ = value;
      }
    }

    /// <summary>Field number for the "CELONKBFKBJ" field.</summary>
    public const int CELONKBFKBJFieldNumber = 1;
    private uint cELONKBFKBJ_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint CELONKBFKBJ {
      get { return cELONKBFKBJ_; }
      set {
        cELONKBFKBJ_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RogueEndlessLayerInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RogueEndlessLayerInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TurnLeftCount != other.TurnLeftCount) return false;
      if (KNNNGLEAJFI != other.KNNNGLEAJFI) return false;
      if (HIEILPMNEHJ != other.HIEILPMNEHJ) return false;
      if (HKKLKELGNFH != other.HKKLKELGNFH) return false;
      if (BattleId != other.BattleId) return false;
      if (HGHNIHOFKOE != other.HGHNIHOFKOE) return false;
      if (JEBFGNMGFNB != other.JEBFGNMGFNB) return false;
      if (CELONKBFKBJ != other.CELONKBFKBJ) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (TurnLeftCount != 0) hash ^= TurnLeftCount.GetHashCode();
      if (KNNNGLEAJFI != 0) hash ^= KNNNGLEAJFI.GetHashCode();
      if (HIEILPMNEHJ != 0) hash ^= HIEILPMNEHJ.GetHashCode();
      if (HKKLKELGNFH != 0) hash ^= HKKLKELGNFH.GetHashCode();
      if (BattleId != 0) hash ^= BattleId.GetHashCode();
      if (HGHNIHOFKOE != 0) hash ^= HGHNIHOFKOE.GetHashCode();
      if (JEBFGNMGFNB != false) hash ^= JEBFGNMGFNB.GetHashCode();
      if (CELONKBFKBJ != 0) hash ^= CELONKBFKBJ.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (CELONKBFKBJ != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(CELONKBFKBJ);
      }
      if (KNNNGLEAJFI != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(KNNNGLEAJFI);
      }
      if (TurnLeftCount != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(TurnLeftCount);
      }
      if (BattleId != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(BattleId);
      }
      if (HGHNIHOFKOE != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(HGHNIHOFKOE);
      }
      if (HIEILPMNEHJ != 0) {
        output.WriteRawTag(80);
        output.WriteUInt32(HIEILPMNEHJ);
      }
      if (JEBFGNMGFNB != false) {
        output.WriteRawTag(104);
        output.WriteBool(JEBFGNMGFNB);
      }
      if (HKKLKELGNFH != 0) {
        output.WriteRawTag(112);
        output.WriteUInt32(HKKLKELGNFH);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (CELONKBFKBJ != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(CELONKBFKBJ);
      }
      if (KNNNGLEAJFI != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(KNNNGLEAJFI);
      }
      if (TurnLeftCount != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(TurnLeftCount);
      }
      if (BattleId != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(BattleId);
      }
      if (HGHNIHOFKOE != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(HGHNIHOFKOE);
      }
      if (HIEILPMNEHJ != 0) {
        output.WriteRawTag(80);
        output.WriteUInt32(HIEILPMNEHJ);
      }
      if (JEBFGNMGFNB != false) {
        output.WriteRawTag(104);
        output.WriteBool(JEBFGNMGFNB);
      }
      if (HKKLKELGNFH != 0) {
        output.WriteRawTag(112);
        output.WriteUInt32(HKKLKELGNFH);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (TurnLeftCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(TurnLeftCount);
      }
      if (KNNNGLEAJFI != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(KNNNGLEAJFI);
      }
      if (HIEILPMNEHJ != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(HIEILPMNEHJ);
      }
      if (HKKLKELGNFH != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(HKKLKELGNFH);
      }
      if (BattleId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(BattleId);
      }
      if (HGHNIHOFKOE != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(HGHNIHOFKOE);
      }
      if (JEBFGNMGFNB != false) {
        size += 1 + 1;
      }
      if (CELONKBFKBJ != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(CELONKBFKBJ);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RogueEndlessLayerInfo other) {
      if (other == null) {
        return;
      }
      if (other.TurnLeftCount != 0) {
        TurnLeftCount = other.TurnLeftCount;
      }
      if (other.KNNNGLEAJFI != 0) {
        KNNNGLEAJFI = other.KNNNGLEAJFI;
      }
      if (other.HIEILPMNEHJ != 0) {
        HIEILPMNEHJ = other.HIEILPMNEHJ;
      }
      if (other.HKKLKELGNFH != 0) {
        HKKLKELGNFH = other.HKKLKELGNFH;
      }
      if (other.BattleId != 0) {
        BattleId = other.BattleId;
      }
      if (other.HGHNIHOFKOE != 0) {
        HGHNIHOFKOE = other.HGHNIHOFKOE;
      }
      if (other.JEBFGNMGFNB != false) {
        JEBFGNMGFNB = other.JEBFGNMGFNB;
      }
      if (other.CELONKBFKBJ != 0) {
        CELONKBFKBJ = other.CELONKBFKBJ;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            CELONKBFKBJ = input.ReadUInt32();
            break;
          }
          case 24: {
            KNNNGLEAJFI = input.ReadUInt32();
            break;
          }
          case 40: {
            TurnLeftCount = input.ReadUInt32();
            break;
          }
          case 48: {
            BattleId = input.ReadUInt32();
            break;
          }
          case 56: {
            HGHNIHOFKOE = input.ReadUInt32();
            break;
          }
          case 80: {
            HIEILPMNEHJ = input.ReadUInt32();
            break;
          }
          case 104: {
            JEBFGNMGFNB = input.ReadBool();
            break;
          }
          case 112: {
            HKKLKELGNFH = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            CELONKBFKBJ = input.ReadUInt32();
            break;
          }
          case 24: {
            KNNNGLEAJFI = input.ReadUInt32();
            break;
          }
          case 40: {
            TurnLeftCount = input.ReadUInt32();
            break;
          }
          case 48: {
            BattleId = input.ReadUInt32();
            break;
          }
          case 56: {
            HGHNIHOFKOE = input.ReadUInt32();
            break;
          }
          case 80: {
            HIEILPMNEHJ = input.ReadUInt32();
            break;
          }
          case 104: {
            JEBFGNMGFNB = input.ReadBool();
            break;
          }
          case 112: {
            HKKLKELGNFH = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
