// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: SceneNpcMonsterInfo.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from SceneNpcMonsterInfo.proto</summary>
  public static partial class SceneNpcMonsterInfoReflection {

    #region Descriptor
    /// <summary>File descriptor for SceneNpcMonsterInfo.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SceneNpcMonsterInfoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChlTY2VuZU5wY01vbnN0ZXJJbmZvLnByb3RvGhlOcGNNb25zdGVyRXh0cmFJ",
            "bmZvLnByb3RvIqQBChNTY2VuZU5wY01vbnN0ZXJJbmZvEhMKC0tISk9OT0pL",
            "SE9JGAEgASgIEhIKCm1vbnN0ZXJfaWQYByABKA0SEAoIZXZlbnRfaWQYCCAB",
            "KA0SEwoLd29ybGRfbGV2ZWwYCiABKA0SEwoLT0xNTUJGT0ZHRUYYCyABKAgS",
            "KAoKZXh0cmFfaW5mbxgNIAEoCzIULk5wY01vbnN0ZXJFeHRyYUluZm9CHqoC",
            "G0VnZ0xpbmsuRGFuaGVuZ1NlcnZlci5Qcm90b2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::EggLink.DanhengServer.Proto.NpcMonsterExtraInfoReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EggLink.DanhengServer.Proto.SceneNpcMonsterInfo), global::EggLink.DanhengServer.Proto.SceneNpcMonsterInfo.Parser, new[]{ "KHJONOJKHOI", "MonsterId", "EventId", "WorldLevel", "OLMMBFOFGEF", "ExtraInfo" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class SceneNpcMonsterInfo : pb::IMessage<SceneNpcMonsterInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SceneNpcMonsterInfo> _parser = new pb::MessageParser<SceneNpcMonsterInfo>(() => new SceneNpcMonsterInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SceneNpcMonsterInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EggLink.DanhengServer.Proto.SceneNpcMonsterInfoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SceneNpcMonsterInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SceneNpcMonsterInfo(SceneNpcMonsterInfo other) : this() {
      kHJONOJKHOI_ = other.kHJONOJKHOI_;
      monsterId_ = other.monsterId_;
      eventId_ = other.eventId_;
      worldLevel_ = other.worldLevel_;
      oLMMBFOFGEF_ = other.oLMMBFOFGEF_;
      extraInfo_ = other.extraInfo_ != null ? other.extraInfo_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SceneNpcMonsterInfo Clone() {
      return new SceneNpcMonsterInfo(this);
    }

    /// <summary>Field number for the "KHJONOJKHOI" field.</summary>
    public const int KHJONOJKHOIFieldNumber = 1;
    private bool kHJONOJKHOI_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool KHJONOJKHOI {
      get { return kHJONOJKHOI_; }
      set {
        kHJONOJKHOI_ = value;
      }
    }

    /// <summary>Field number for the "monster_id" field.</summary>
    public const int MonsterIdFieldNumber = 7;
    private uint monsterId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint MonsterId {
      get { return monsterId_; }
      set {
        monsterId_ = value;
      }
    }

    /// <summary>Field number for the "event_id" field.</summary>
    public const int EventIdFieldNumber = 8;
    private uint eventId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint EventId {
      get { return eventId_; }
      set {
        eventId_ = value;
      }
    }

    /// <summary>Field number for the "world_level" field.</summary>
    public const int WorldLevelFieldNumber = 10;
    private uint worldLevel_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint WorldLevel {
      get { return worldLevel_; }
      set {
        worldLevel_ = value;
      }
    }

    /// <summary>Field number for the "OLMMBFOFGEF" field.</summary>
    public const int OLMMBFOFGEFFieldNumber = 11;
    private bool oLMMBFOFGEF_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool OLMMBFOFGEF {
      get { return oLMMBFOFGEF_; }
      set {
        oLMMBFOFGEF_ = value;
      }
    }

    /// <summary>Field number for the "extra_info" field.</summary>
    public const int ExtraInfoFieldNumber = 13;
    private global::EggLink.DanhengServer.Proto.NpcMonsterExtraInfo extraInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::EggLink.DanhengServer.Proto.NpcMonsterExtraInfo ExtraInfo {
      get { return extraInfo_; }
      set {
        extraInfo_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SceneNpcMonsterInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SceneNpcMonsterInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (KHJONOJKHOI != other.KHJONOJKHOI) return false;
      if (MonsterId != other.MonsterId) return false;
      if (EventId != other.EventId) return false;
      if (WorldLevel != other.WorldLevel) return false;
      if (OLMMBFOFGEF != other.OLMMBFOFGEF) return false;
      if (!object.Equals(ExtraInfo, other.ExtraInfo)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (KHJONOJKHOI != false) hash ^= KHJONOJKHOI.GetHashCode();
      if (MonsterId != 0) hash ^= MonsterId.GetHashCode();
      if (EventId != 0) hash ^= EventId.GetHashCode();
      if (WorldLevel != 0) hash ^= WorldLevel.GetHashCode();
      if (OLMMBFOFGEF != false) hash ^= OLMMBFOFGEF.GetHashCode();
      if (extraInfo_ != null) hash ^= ExtraInfo.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (KHJONOJKHOI != false) {
        output.WriteRawTag(8);
        output.WriteBool(KHJONOJKHOI);
      }
      if (MonsterId != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(MonsterId);
      }
      if (EventId != 0) {
        output.WriteRawTag(64);
        output.WriteUInt32(EventId);
      }
      if (WorldLevel != 0) {
        output.WriteRawTag(80);
        output.WriteUInt32(WorldLevel);
      }
      if (OLMMBFOFGEF != false) {
        output.WriteRawTag(88);
        output.WriteBool(OLMMBFOFGEF);
      }
      if (extraInfo_ != null) {
        output.WriteRawTag(106);
        output.WriteMessage(ExtraInfo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (KHJONOJKHOI != false) {
        output.WriteRawTag(8);
        output.WriteBool(KHJONOJKHOI);
      }
      if (MonsterId != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(MonsterId);
      }
      if (EventId != 0) {
        output.WriteRawTag(64);
        output.WriteUInt32(EventId);
      }
      if (WorldLevel != 0) {
        output.WriteRawTag(80);
        output.WriteUInt32(WorldLevel);
      }
      if (OLMMBFOFGEF != false) {
        output.WriteRawTag(88);
        output.WriteBool(OLMMBFOFGEF);
      }
      if (extraInfo_ != null) {
        output.WriteRawTag(106);
        output.WriteMessage(ExtraInfo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (KHJONOJKHOI != false) {
        size += 1 + 1;
      }
      if (MonsterId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MonsterId);
      }
      if (EventId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(EventId);
      }
      if (WorldLevel != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(WorldLevel);
      }
      if (OLMMBFOFGEF != false) {
        size += 1 + 1;
      }
      if (extraInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ExtraInfo);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SceneNpcMonsterInfo other) {
      if (other == null) {
        return;
      }
      if (other.KHJONOJKHOI != false) {
        KHJONOJKHOI = other.KHJONOJKHOI;
      }
      if (other.MonsterId != 0) {
        MonsterId = other.MonsterId;
      }
      if (other.EventId != 0) {
        EventId = other.EventId;
      }
      if (other.WorldLevel != 0) {
        WorldLevel = other.WorldLevel;
      }
      if (other.OLMMBFOFGEF != false) {
        OLMMBFOFGEF = other.OLMMBFOFGEF;
      }
      if (other.extraInfo_ != null) {
        if (extraInfo_ == null) {
          ExtraInfo = new global::EggLink.DanhengServer.Proto.NpcMonsterExtraInfo();
        }
        ExtraInfo.MergeFrom(other.ExtraInfo);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            KHJONOJKHOI = input.ReadBool();
            break;
          }
          case 56: {
            MonsterId = input.ReadUInt32();
            break;
          }
          case 64: {
            EventId = input.ReadUInt32();
            break;
          }
          case 80: {
            WorldLevel = input.ReadUInt32();
            break;
          }
          case 88: {
            OLMMBFOFGEF = input.ReadBool();
            break;
          }
          case 106: {
            if (extraInfo_ == null) {
              ExtraInfo = new global::EggLink.DanhengServer.Proto.NpcMonsterExtraInfo();
            }
            input.ReadMessage(ExtraInfo);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            KHJONOJKHOI = input.ReadBool();
            break;
          }
          case 56: {
            MonsterId = input.ReadUInt32();
            break;
          }
          case 64: {
            EventId = input.ReadUInt32();
            break;
          }
          case 80: {
            WorldLevel = input.ReadUInt32();
            break;
          }
          case 88: {
            OLMMBFOFGEF = input.ReadBool();
            break;
          }
          case 106: {
            if (extraInfo_ == null) {
              ExtraInfo = new global::EggLink.DanhengServer.Proto.NpcMonsterExtraInfo();
            }
            input.ReadMessage(ExtraInfo);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
