// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: SpaceZooMutateScRsp.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from SpaceZooMutateScRsp.proto</summary>
  public static partial class SpaceZooMutateScRspReflection {

    #region Descriptor
    /// <summary>File descriptor for SpaceZooMutateScRsp.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SpaceZooMutateScRspReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChlTcGFjZVpvb011dGF0ZVNjUnNwLnByb3RvGhFLSkVQTEZQQUxDQi5wcm90",
            "bxoRREdEUE9DTkZOQk0ucHJvdG8igQEKE1NwYWNlWm9vTXV0YXRlU2NSc3AS",
            "IQoLSUZQSk9QUERKR0EYDSABKAsyDC5ER0RQT0NORk5CTRIPCgdyZXRjb2Rl",
            "GA8gASgNEiEKC0tPUE1DRlBBUEVMGAEgAygLMgwuS0pFUExGUEFMQ0ISEwoL",
            "TkVQTFBPRENIUEUYCyABKAhCHqoCG0VnZ0xpbmsuRGFuaGVuZ1NlcnZlci5Q",
            "cm90b2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::EggLink.DanhengServer.Proto.KJEPLFPALCBReflection.Descriptor, global::EggLink.DanhengServer.Proto.DGDPOCNFNBMReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EggLink.DanhengServer.Proto.SpaceZooMutateScRsp), global::EggLink.DanhengServer.Proto.SpaceZooMutateScRsp.Parser, new[]{ "IFPJOPPDJGA", "Retcode", "KOPMCFPAPEL", "NEPLPODCHPE" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class SpaceZooMutateScRsp : pb::IMessage<SpaceZooMutateScRsp>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SpaceZooMutateScRsp> _parser = new pb::MessageParser<SpaceZooMutateScRsp>(() => new SpaceZooMutateScRsp());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SpaceZooMutateScRsp> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EggLink.DanhengServer.Proto.SpaceZooMutateScRspReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SpaceZooMutateScRsp() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SpaceZooMutateScRsp(SpaceZooMutateScRsp other) : this() {
      iFPJOPPDJGA_ = other.iFPJOPPDJGA_ != null ? other.iFPJOPPDJGA_.Clone() : null;
      retcode_ = other.retcode_;
      kOPMCFPAPEL_ = other.kOPMCFPAPEL_.Clone();
      nEPLPODCHPE_ = other.nEPLPODCHPE_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SpaceZooMutateScRsp Clone() {
      return new SpaceZooMutateScRsp(this);
    }

    /// <summary>Field number for the "IFPJOPPDJGA" field.</summary>
    public const int IFPJOPPDJGAFieldNumber = 13;
    private global::EggLink.DanhengServer.Proto.DGDPOCNFNBM iFPJOPPDJGA_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::EggLink.DanhengServer.Proto.DGDPOCNFNBM IFPJOPPDJGA {
      get { return iFPJOPPDJGA_; }
      set {
        iFPJOPPDJGA_ = value;
      }
    }

    /// <summary>Field number for the "retcode" field.</summary>
    public const int RetcodeFieldNumber = 15;
    private uint retcode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Retcode {
      get { return retcode_; }
      set {
        retcode_ = value;
      }
    }

    /// <summary>Field number for the "KOPMCFPAPEL" field.</summary>
    public const int KOPMCFPAPELFieldNumber = 1;
    private static readonly pb::FieldCodec<global::EggLink.DanhengServer.Proto.KJEPLFPALCB> _repeated_kOPMCFPAPEL_codec
        = pb::FieldCodec.ForMessage(10, global::EggLink.DanhengServer.Proto.KJEPLFPALCB.Parser);
    private readonly pbc::RepeatedField<global::EggLink.DanhengServer.Proto.KJEPLFPALCB> kOPMCFPAPEL_ = new pbc::RepeatedField<global::EggLink.DanhengServer.Proto.KJEPLFPALCB>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::EggLink.DanhengServer.Proto.KJEPLFPALCB> KOPMCFPAPEL {
      get { return kOPMCFPAPEL_; }
    }

    /// <summary>Field number for the "NEPLPODCHPE" field.</summary>
    public const int NEPLPODCHPEFieldNumber = 11;
    private bool nEPLPODCHPE_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool NEPLPODCHPE {
      get { return nEPLPODCHPE_; }
      set {
        nEPLPODCHPE_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SpaceZooMutateScRsp);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SpaceZooMutateScRsp other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(IFPJOPPDJGA, other.IFPJOPPDJGA)) return false;
      if (Retcode != other.Retcode) return false;
      if(!kOPMCFPAPEL_.Equals(other.kOPMCFPAPEL_)) return false;
      if (NEPLPODCHPE != other.NEPLPODCHPE) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (iFPJOPPDJGA_ != null) hash ^= IFPJOPPDJGA.GetHashCode();
      if (Retcode != 0) hash ^= Retcode.GetHashCode();
      hash ^= kOPMCFPAPEL_.GetHashCode();
      if (NEPLPODCHPE != false) hash ^= NEPLPODCHPE.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      kOPMCFPAPEL_.WriteTo(output, _repeated_kOPMCFPAPEL_codec);
      if (NEPLPODCHPE != false) {
        output.WriteRawTag(88);
        output.WriteBool(NEPLPODCHPE);
      }
      if (iFPJOPPDJGA_ != null) {
        output.WriteRawTag(106);
        output.WriteMessage(IFPJOPPDJGA);
      }
      if (Retcode != 0) {
        output.WriteRawTag(120);
        output.WriteUInt32(Retcode);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      kOPMCFPAPEL_.WriteTo(ref output, _repeated_kOPMCFPAPEL_codec);
      if (NEPLPODCHPE != false) {
        output.WriteRawTag(88);
        output.WriteBool(NEPLPODCHPE);
      }
      if (iFPJOPPDJGA_ != null) {
        output.WriteRawTag(106);
        output.WriteMessage(IFPJOPPDJGA);
      }
      if (Retcode != 0) {
        output.WriteRawTag(120);
        output.WriteUInt32(Retcode);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (iFPJOPPDJGA_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(IFPJOPPDJGA);
      }
      if (Retcode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Retcode);
      }
      size += kOPMCFPAPEL_.CalculateSize(_repeated_kOPMCFPAPEL_codec);
      if (NEPLPODCHPE != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SpaceZooMutateScRsp other) {
      if (other == null) {
        return;
      }
      if (other.iFPJOPPDJGA_ != null) {
        if (iFPJOPPDJGA_ == null) {
          IFPJOPPDJGA = new global::EggLink.DanhengServer.Proto.DGDPOCNFNBM();
        }
        IFPJOPPDJGA.MergeFrom(other.IFPJOPPDJGA);
      }
      if (other.Retcode != 0) {
        Retcode = other.Retcode;
      }
      kOPMCFPAPEL_.Add(other.kOPMCFPAPEL_);
      if (other.NEPLPODCHPE != false) {
        NEPLPODCHPE = other.NEPLPODCHPE;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            kOPMCFPAPEL_.AddEntriesFrom(input, _repeated_kOPMCFPAPEL_codec);
            break;
          }
          case 88: {
            NEPLPODCHPE = input.ReadBool();
            break;
          }
          case 106: {
            if (iFPJOPPDJGA_ == null) {
              IFPJOPPDJGA = new global::EggLink.DanhengServer.Proto.DGDPOCNFNBM();
            }
            input.ReadMessage(IFPJOPPDJGA);
            break;
          }
          case 120: {
            Retcode = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            kOPMCFPAPEL_.AddEntriesFrom(ref input, _repeated_kOPMCFPAPEL_codec);
            break;
          }
          case 88: {
            NEPLPODCHPE = input.ReadBool();
            break;
          }
          case 106: {
            if (iFPJOPPDJGA_ == null) {
              IFPJOPPDJGA = new global::EggLink.DanhengServer.Proto.DGDPOCNFNBM();
            }
            input.ReadMessage(IFPJOPPDJGA);
            break;
          }
          case 120: {
            Retcode = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
